title: "Name me "
labels: ["type: security report :rotating_light:"]
body:
  - type: textarea
    id: content
    attributes:
      label: Not required
      value: |
        > [!CAUTION]
        Embrace AI's 10x power, or watch the future built without you. :robot:

        ## User role

        1.

        ## Intended Outcome

        1.

        ## Benefits

        1.

        ## How it'll work

        1.

        ## Acceptance Criteria

        1.

        ## Context

        1.

        If needed, feel free to add an alert using the format described in the [GitHub Docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts)

  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: The Code of Conduct helps create a safe and better space for everyone. We require
        that everyone agrees to it.
      options:
        - label: I agree to follow this project's [Code of Conduct](link/to/coc)
          required: true