name: Credential 🔑
description: Access requests or management for systems/services.
type: 'Credential 🔑'
projects: ["StaytunedLLP/17"]

body:
  - type: markdown
    attributes:
      value: Let AI build, be orchestrator, ship instantly. 🤖🪄🚀
      
  - type: textarea
    attributes:
      label: Description
      value: |
        ### Request 

        1. User:
        2. System: 
        3. Role: 

        ### Duration

        - [ ] Permanent
        - [ ] Temporary (Until: YYYY-MM-DD)

        ### Protocol

        - [ ] 2FA enabled
        - [ ] Security policy reviewed

        ### Delivery Method

        ** Do NOT paste password or secrets here.**
        
        1. Share via either saved password in browser or secure vault (e.g., 1Password, LastPass).
        2. Share via encrypted DM.

        ### Context
