name: Start Coding
on:
  workflow_call:

jobs:
  dispatch-start-coding:
    runs-on: [self-hosted, pi4b-01]
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get issue detail
        id: get_issue_detail
        run: |
          echo "issue_number=${{ github.event.issue.number }}" >> $GITHUB_ENV
          echo "issue_title=${{ github.event.issue.title }}" >> $GITHUB_ENV
          echo "issue_assignee=${{ github.event.issue.assignee.login }}" >> $GITHUB_ENV

      - name: Get Owner and Repo Name
        run: |
          OWNER=$(echo ${{ github.repository }} | cut -d/ -f1)
          REPO=$(echo ${{ github.repository }} | cut -d/ -f2)
          echo "github_owner=$OWNER" >> $GITHUB_ENV
          echo "github_repo=$REPO" >> $GITHUB_ENV

      - name: Trigger event
        env:
          APP_ID: ${{ secrets.DISPATCH_BOT_APP_ID }}
          PRIVATE_KEY: ${{ secrets.DISPATCH_BOT_PPK }}
          INSTALLATION_ID: ${{ secrets.DISPATCH_BOT_INSTALLATION_ID }}
          EVENT_TYPE: start-coding
          CLIENT_PAYLOAD: '{ "issue_number": "${{env.issue_number}}", "issue_title": "${{env.issue_title}}", "issue_assigneelogin": "${{env.issue_assignee}}" , "owner": "${{env.github_owner}}", "repo": "${{env.github_repo}}", "pr_body": "Hello world!!"}'
        run: |
          if [[ "$(uname)" == "Darwin" ]]; then
             DAGGER_PATH=$(echo $(readlink -f /opt/homebrew/bin/dagger) | sed 's|\(.*\)/dagger|\1|')
             JQ_PATH=$(echo $(readlink -f /opt/homebrew/bin/jq) | sed 's|\(.*\)/jq|\1|')
             PATH=$PATH:$DAGGER_PATH:$JQ_PATH
           # else
           #   echo "::add-path::/usr/bin"
           fi
            echo $PATH
          cd .github/workflows && dagger run ./build.sh & wait $!
